### ISSUE TITLE
About "Validation" errors in yml

### ISSUE THREAD

**Issue by animeojisan** [the-database/traiNNer-redux#19]
I used it on Windows.
It seems like there's an extra space here.

```
#############
# Validation
#############
# Uncomment these for validation.
# val:
#   val_freq: 1000
#   save_img: True

#   metrics:
#     psnr:
#       type: calculate_psnr
#       crop_border: 4
#       test_y_channel: false
#     ssim:
#       type: calculate_ssim
#       crop_border: 4  # Whether to crop border during validation.
#       test_y_channel: false  # Whether to convert to Y(CbCr) for validation.
#     dists:
#       type: calculate_dists
#       better: lower
```
Removing the # above still results in an error.

```
#############
# Validation
#############
# Uncomment these for validation.
val:
  val_freq: 1000
  save_img: True

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4  # Whether to crop border during validation.
      test_y_channel: false  # Whether to convert to Y(CbCr) for validation.
    dists:
      type: calculate_dists
      better: lower
```

The above will work properly.　

```
#############
# Validation
#############
# Uncomment these for validation.
#val:
#  val_freq: 1000
#  save_img: True

#  metrics:
#    psnr:
#      type: calculate_psnr
#      crop_border: 4
#      test_y_channel: false
#    ssim:
#      type: calculate_ssim
#      crop_border: 4  # Whether to crop border during validation.
#      test_y_channel: false  # Whether to convert to Y(CbCr) for validation.
#    dists:
#      type: calculate_dists
#      better: lower
```
I think the right thing to do is this.
I apologize if I have pointed out some misunderstanding.
