### ISSUE TITLE
Error starting TSCUNet training

### ISSUE THREAD

**Issue by sonic41592** [the-database/traiNNer-redux#233]
Hello! I get the following error when trying to start training a TSCUNet model, it looks like the tensor created for the temporal network has the wrong parameters

[02/18/25 16:03:36] INFO     Start training from epoch: 0, iter: 0.                                         train.py:372
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\traiNNer-redux-master\train.py:522 in <module>                                                │
│                                                                                                  │
│   519                                                                                            │
│   520 if __name__ == "__main__":                                                                 │
│   521 │   root_path = osp.abspath(osp.join(__file__, osp.pardir))                                │
│ ❱ 522 │   train_pipeline(root_path)                                                              │
│   523                                                                                            │
│                                                                                                  │
│ E:\traiNNer-redux-master\train.py:412 in train_pipeline                                          │
│                                                                                                  │
│   409 │   │   │   # training                                                                     │
│   410 │   │   │   model.feed_data(train_data)                                                    │
│   411 │   │   │   try:                                                                           │
│ ❱ 412 │   │   │   │   model.optimize_parameters(                                                 │
│   413 │   │   │   │   │   current_iter, current_accum_iter, apply_gradient                       │
│   414 │   │   │   │   )                                                                          │
│   415 │   │   │   except RuntimeError as e:                                                      │
│                                                                                                  │
│ E:\traiNNer-redux-master\traiNNer\models\sr_model.py:352 in optimize_parameters                  │
│                                                                                                  │
│   349 │   │   with torch.autocast(                                                               │
│   350 │   │   │   device_type=self.device.type, dtype=self.amp_dtype, enabled=self.use_amp       │
│   351 │   │   ):                                                                                 │
│ ❱ 352 │   │   │   self.output = self.net_g(self.lq)                                              │
│   353 │   │   │   assert isinstance(self.output, Tensor)                                         │
│   354 │   │   │   l_g_total = torch.tensor(0.0, device=self.output.device)                       │
│   355 │   │   │   loss_dict = OrderedDict()                                                      │
│                                                                                                  │
│ C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module. │
│ py:1736 in _wrapped_call_impl                                                                    │
│                                                                                                  │
│   1733 │   │   if self._compiled_call_impl is not None:                                          │
│   1734 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1735 │   │   else:                                                                             │
│ ❱ 1736 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1737 │                                                                                         │
│   1738 │   # torchrec tests the code consistency with the following code                         │
│   1739 │   # fmt: off                                                                            │
│                                                                                                  │
│ C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module. │
│ py:1747 in _call_impl                                                                            │
│                                                                                                  │
│   1744 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1745 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1746 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1747 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1748 │   │                                                                                     │
│   1749 │   │   result = None                                                                     │
│   1750 │   │   called_always_called_hooks = set()                                                │
│                                                                                                  │
│ E:\traiNNer-redux-master\traiNNer\archs\tscunet_arch.py:298 in forward                           │
│                                                                                                  │
│   295 │   │   │   self.load_state_dict(state, strict=True)                                       │
│   296 │                                                                                          │
│   297 │   def forward(self, x):                                                                  │
│ ❱ 298 │   │   b, t, c, h, w = x.size()                                                           │
│   299 │   │   if t != self.clip_size:                                                            │
│   300 │   │   │   raise ValueError(                                                              │
│   301 │   │   │   │   f"input clip size {t} does not match model clip size {self.clip_size}"     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by the-database** [comment]
Hi, just tested and it seems to be working on my end. Could you please share your training config yml?

**Comment by sonic41592** [comment]
Sure! I was using the basic TSCUNet_OTF_fromscratch config, just the dataset paths and the scale have been changed

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# General Settings
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#top-level-options
#########################################################################################
name: 2x_TSCUNet_OTF_fromscratch
scale: 2  # 1, 2, 4, 8
use_amp: true  # Speed up training and reduce VRAM usage. NVIDIA only.
amp_bf16: false  # Use bf16 instead of fp16 for AMP, RTX 3000 series or newer only. Only recommended if fp16 doesn't work.
use_channels_last: true  # Enable channels last memory format while using AMP. Reduces VRAM and speeds up training for most architectures, but some architectures are slower with channels last.
fast_matmul: false  # Trade precision for performance.
num_gpu: auto
# manual_seed: 1024  # Deterministic mode, slows down training.

high_order_degradation: true  # Enable on-the-fly (OTF) degradations, which generates LR tiles from HRs during training.
high_order_degradations_debug: false  # Save the LR and HR tiles to debug/otf folder inside the root of the training directory.
high_order_degradations_debug_limit: 100  # The max number of iterations to save LR and HR tiles for.

# USM degradation options.
lq_usm: false  # Apply unsharp mask to LQ image before all other degradations.
lq_usm_radius_range: [1, 25]  # Range of randomly selected unsharp mask radius to apply.

# The first degradation process.
blur_prob: 0.0
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_mode_list: ['bilinear', 'bicubic', 'nearest-exact', 'lanczos']  # bilinear, bicubic, nearest-exact, lanczos
resize_mode_prob: [0.25, 0.25, 0.25, 0.25]  # Probability each resize mode is selected.
resize_range: [0.4, 1.5]
gaussian_noise_prob: 0.0
noise_range: [0, 0]
poisson_scale_range: [0, 0]
gray_noise_prob: 0.0
jpeg_prob: 1.0
jpeg_range: [75, 95]

# The second degradation process.
blur_prob2: 0.0
resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
resize_mode_list2: ['bilinear', 'bicubic', 'nearest-exact', 'lanczos']  # bilinear, bicubic, nearest-exact, lanczos
resize_mode_prob2: [0.25, 0.25, 0.25, 0.25]  # Probability each resize mode is selected.
resize_range2: [0.6, 1.2]
gaussian_noise_prob2: 0
noise_range2: [0, 0]
poisson_scale_range2: [0, 0]
gray_noise_prob2: 0.0
jpeg_prob2: 1.0
jpeg_range2: [75, 95]

# The final resize to the target resolution.
resize_mode_list3: ['bilinear', 'bicubic', 'nearest-exact', 'lanczos']  # bilinear, bicubic, nearest-exact, lanczos
resize_mode_prob3: [0.25, 0.25, 0.25, 0.25]  # Probability each resize mode is selected.

queue_size: 120

########################################################################################################################
# Dataset and Dataloader Settings
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#dataset-options-datasets-train-and-datasets-val
########################################################################################################################
datasets:
  # Settings for the training dataset.
  train:
    name: Train Dataset
    type: realesrgandataset
    # Path to the HR (high res) images in your training dataset. Specify one or multiple folders, separated by commas.
    dataroot_gt: [
      datasets/train/dataset1/hr,
    ]
    # Path to the LR (low res) images in your training dataset. Specify one or multiple folders, separated by commas.
    # meta_info: data/meta_info/dataset1.txt

    blur_kernel_size: 12
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    kernel_range: [5, 17]  # kernel range inclusive, must be odd numbers
    sinc_prob: 0.0
    blur_sigma: [0.2, 2]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 12
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    kernel_range2: [5, 17]  # kernel range inclusive, must be odd numbers
    sinc_prob2: 0.0
    blur_sigma2: [0.2, 1]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.0
    final_kernel_range: [5, 17]  # kernel range inclusive, must be odd numbers

    lq_size: 64  # During training, a square of this size is cropped from LR images. Larger is usually better but uses more VRAM. Previously gt_size, use lq_size = gt_size / scale to convert. Use multiple of 8 for best performance with AMP.
    use_hflip: true  # Randomly flip the images horizontally.
    use_rot: true  # Randomly rotate the images.

    num_worker_per_gpu: 8
    batch_size_per_gpu: 8  # Increasing stabilizes training but going too high can cause issues. Use multiple of 8 for best performance with AMP.
    accum_iter: 1  # Using values larger than 1 simulates higher batch size by trading performance for reduced VRAM usage. If accum_iter = 4 and batch_size_per_gpu = 6 then effective batch size = 4 * 6 = 24 but performance may be as much as 4 times as slow.
  # Settings for your validation dataset (optional). These settings will
  # be ignored if val_enabled is false in the Validation section below.
  val:
    name: Val Dataset
    type: pairedvideodataset
    dataroot_gt: [
      datasets/val/dataset1/hrtest,
    ]
    dataroot_lq: [
      datasets/val/dataset1/lrtest,
    ]
    clip_size: 5

#####################################################################
# Network Settings
# https://trainner-redux.readthedocs.io/en/latest/arch_reference.html
#####################################################################
# Generator model settings
network_g:
  type: tscunet

#########################################################################################
# Pretrain and Resume Paths
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#path-options-path
#########################################################################################
path:
  resume_state: ~

###########################################################################################
# Training Settings
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#train-options-train
###########################################################################################
train:
  ema_decay: 0.999
  grad_clip: false  # Gradient clipping allows more stable training when using higher learning rates.
  # Optimizer for generator model
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000  # Total number of iterations.
  warmup_iter: -1  # Gradually ramp up learning rates until this iteration, to stabilize early training. Use -1 to disable.

  # Losses - for any loss set the loss_weight to 0 to disable it.
  # https://trainner-redux.readthedocs.io/en/latest/loss_reference.html
  losses:
    # MS-SSIM L1 loss
    - type: msssiml1loss
      alpha: 0.1
      loss_weight: 1.0

##############################################################################################
# Validation
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#validation-options-val
##############################################################################################
val:
  val_enabled: false  # Whether to enable validations. If disabled, all validation settings below are ignored.
  val_freq: 1000  # How often to run validations, in iterations.
  save_img: true  # Whether to save the validation images during validation, in the experiments/<name>/visualization folder.

  metrics_enabled: true  # Whether to run metrics calculations during validation.
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4  # Whether to crop border during validation.
      test_y_channel: false  # Whether to convert to Y(CbCr) for validation.
    dists:
      type: calculate_dists
      better: lower

##############################################################################################
# Logging
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#logging-options-logger
##############################################################################################
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  save_checkpoint_format: pth
  use_tb_logger: true
```

**Comment by the-database** [comment]
Thanks, I see, I was testing paired rather than OTF, which is why I wasn't reproducing the error earlier. It looks like OTF doesn't work with TSCUNet at the moment, which is a bug. Although I actually would recommend not using OTF with TSCUNet for now.

The current OTF implementation is based on the Real ESRGAN degradation pipeline, which applies single image degradation like JPEG, noise, blur, etc. Since it doesn't apply any video degradation, there is not much benefit to using a temporally aware network like TSCUNet. 

The best way to use TSCUNet at the moment is with the paired video dataset. You can create compressed videos, and then dump sequential LR frames. These LR frames will have temporal artifacts from video compression, which TSCUNet should be effective in removing.

In the future it would be interesting if OTF could be extended to apply video degradations to image sequences, but it may be too slow to run in realtime during training.

**Comment by sonic41592** [comment]
Thanks for the info! I get this similar error when trying to run as a paired dataset.  This is using the basic TSCUNet_fromscratch.yml on a new install of Windows. I was able to train on this arch a while back, possibly around August/September last year. I'll post the configuration file too. 
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Training\traiNNer-redux-master\train.py:522 in <module>                                       │
│                                                                                                  │
│   519                                                                                            │
│   520 if __name__ == "__main__":                                                                 │
│   521 │   root_path = osp.abspath(osp.join(__file__, osp.pardir))                                │
│ ❱ 522 │   train_pipeline(root_path)                                                              │
│   523                                                                                            │
│                                                                                                  │
│ D:\Training\traiNNer-redux-master\train.py:410 in train_pipeline                                 │
│                                                                                                  │
│   407 │   │   │   if current_iter > total_iters:                                                 │
│   408 │   │   │   │   break                                                                      │
│   409 │   │   │   # training                                                                     │
│ ❱ 410 │   │   │   model.feed_data(train_data)                                                    │
│   411 │   │   │   try:                                                                           │
│   412 │   │   │   │   model.optimize_parameters(                                                 │
│   413 │   │   │   │   │   current_iter, current_accum_iter, apply_gradient                       │
│                                                                                                  │
│ D:\Training\traiNNer-redux-master\traiNNer\models\sr_model.py:314 in feed_data                   │
│                                                                                                  │
│   311 │                                                                                          │
│   312 │   def feed_data(self, data: DataFeed) -> None:                                           │
│   313 │   │   assert "lq" in data                                                                │
│ ❱ 314 │   │   self.lq = data["lq"].to(                                                           │
│   315 │   │   │   self.device,                                                                   │
│   316 │   │   │   memory_format=self.memory_format,                                              │
│   317 │   │   │   non_blocking=True,                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: required rank 4 tensor to use channels_last format
```

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/the-database/traiNNer-redux/refs/heads/master/schemas/redux-config.schema.json
#########################################################################################
# General Settings
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#top-level-options
#########################################################################################
name: 2x_TSCUNet
scale: 2  # 1, 2, 4, 8
use_amp: true  # Speed up training and reduce VRAM usage. NVIDIA only.
amp_bf16: false  # Use bf16 instead of fp16 for AMP, RTX 3000 series or newer only. Only recommended if fp16 doesn't work.
use_channels_last: true  # Enable channels last memory format while using AMP. Reduces VRAM and speeds up training for most architectures, but some architectures are slower with channels last.
fast_matmul: false  # Trade precision for performance.
num_gpu: auto
# manual_seed: 1024  # Deterministic mode, slows down training.


########################################################################################################################
# Dataset and Dataloader Settings
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#dataset-options-datasets-train-and-datasets-val
########################################################################################################################
datasets:
  # Settings for the training dataset.
  train:
    name: Train Dataset
    type: pairedvideodataset
    # Path to the HR (high res) images in your training dataset. Specify one or multiple folders, separated by commas.
    dataroot_gt: [
      datasets/train/video/hr,
    ]
    # Path to the LR (low res) images in your training dataset. Specify one or multiple folders, separated by commas.
    dataroot_lq: [
      datasets/train/video/lr,
    ]
    clip_size: 5
    # meta_info: data/meta_info/dataset1.txt


    lq_size: 64  # During training, a square of this size is cropped from LR images. Larger is usually better but uses more VRAM. Previously gt_size, use lq_size = gt_size / scale to convert. Use multiple of 8 for best performance with AMP.
    use_hflip: true  # Randomly flip the images horizontally.
    use_rot: true  # Randomly rotate the images.

    num_worker_per_gpu: 8
    batch_size_per_gpu: 8  # Increasing stabilizes training but going too high can cause issues. Use multiple of 8 for best performance with AMP.
    accum_iter: 1  # Using values larger than 1 simulates higher batch size by trading performance for reduced VRAM usage. If accum_iter = 4 and batch_size_per_gpu = 6 then effective batch size = 4 * 6 = 24 but performance may be as much as 4 times as slow.
  # Settings for your validation dataset (optional). These settings will
  # be ignored if val_enabled is false in the Validation section below.
  val:
    name: Val Dataset
    type: pairedvideodataset
    dataroot_gt: [
      datasets/val/video/hr,
    ]
    dataroot_lq: [
      datasets/val/video/lr,
    ]
    clip_size: 5

#####################################################################
# Network Settings
# https://trainner-redux.readthedocs.io/en/latest/arch_reference.html
#####################################################################
# Generator model settings
network_g:
  type: tscunet

#########################################################################################
# Pretrain and Resume Paths
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#path-options-path
#########################################################################################
path:
  resume_state: ~

###########################################################################################
# Training Settings
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#train-options-train
###########################################################################################
train:
  ema_decay: 0.999
  grad_clip: false  # Gradient clipping allows more stable training when using higher learning rates.
  # Optimizer for generator model
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000  # Total number of iterations.
  warmup_iter: -1  # Gradually ramp up learning rates until this iteration, to stabilize early training. Use -1 to disable.

  # Losses - for any loss set the loss_weight to 0 to disable it.
  # https://trainner-redux.readthedocs.io/en/latest/loss_reference.html
  losses:
    # MS-SSIM L1 loss
    - type: msssiml1loss
      alpha: 0.1
      loss_weight: 1.0

##############################################################################################
# Validation
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#validation-options-val
##############################################################################################
val:
  val_enabled: false  # Whether to enable validations. If disabled, all validation settings below are ignored.
  val_freq: 1000  # How often to run validations, in iterations.
  save_img: true  # Whether to save the validation images during validation, in the experiments/<name>/visualization folder.

  metrics_enabled: true  # Whether to run metrics calculations during validation.
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4  # Whether to crop border during validation.
      test_y_channel: false  # Whether to convert to Y(CbCr) for validation.
    dists:
      type: calculate_dists
      better: lower

##############################################################################################
# Logging
# https://trainner-redux.readthedocs.io/en/latest/config_reference.html#logging-options-logger
##############################################################################################
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  save_checkpoint_format: pth
  use_tb_logger: true

```
